products:
  log4j-scanner:
    build:
      main-pkg: .
      version-var: github.com/palantir/log4j-scanner/cmd.Version
      os-archs:
      - os: linux
        arch: amd64
      - os: darwin
        arch: amd64
      - os: darwin
        arch: arm64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
            - os: linux
              arch: amd64
            - os: darwin
              arch: amd64
            - os: darwin
              arch: arm64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.log4j-scanner
