environment:
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated
  paths:
    - godel
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.16.0
        checksums:
          darwin-amd64: af151616fcba24be861f4fff6c3df7f8874391f70372d302e38ac7d52bd7cfc3
          linux-amd64: cc31979897dc8f30e0c8c8d8abba65eb23e2171323ff299edeeb21fa2b028315
