/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package light_shading;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.lookup.JndiLookup;

public class App {
    private static Logger logger = LogManager.getLogger();

    public String getGreeting() {
        return JndiLookup.class.getName();
    }

    public static void main(String[] args) {
        logger.fatal("Logging uses a bad version of log4j");
        System.out.println(new App().getGreeting());
    }
}
